<?php
/**
 * SendApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Invoicetronic
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Italian eInvoice API
 *
 * The Italian eInvoice API is a RESTful API that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed by Invoicetronic to be simple and easy to use, abstracting away SDI complexity while still providing complete control over the invoice send/receive process. The API also provides advanced features and a rich toolchain, such as invoice validation, multiple upload methods, webhooks, event logs, CORS support, client SDKs for commonly used languages, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@invoicetronic.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Invoicetronic\Test\Api;

use \Invoicetronic\Configuration;
use \Invoicetronic\ApiException;
use \Invoicetronic\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SendApiTest Class Doc Comment
 *
 * @category Class
 * @package  Invoicetronic
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SendApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for invoiceV1SendFilesPost
     *
     * Add an invoice by file.
     *
     */
    public function testInvoiceV1SendFilesPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for invoiceV1SendGet
     *
     * List invoices.
     *
     */
    public function testInvoiceV1SendGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for invoiceV1SendIdGet
     *
     * Get a invoice by id.
     *
     */
    public function testInvoiceV1SendIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for invoiceV1SendJsonPost
     *
     * Add an invoice by json.
     *
     */
    public function testInvoiceV1SendJsonPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for invoiceV1SendPost
     *
     * Add an invoice.
     *
     */
    public function testInvoiceV1SendPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for invoiceV1SendValidateFilesPost
     *
     * Validate an invoice by file.
     *
     */
    public function testInvoiceV1SendValidateFilesPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for invoiceV1SendValidateJsonPost
     *
     * Validate an invoice by json.
     *
     */
    public function testInvoiceV1SendValidateJsonPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for invoiceV1SendValidatePost
     *
     * Validate an invoice.
     *
     */
    public function testInvoiceV1SendValidatePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for invoiceV1SendValidateXmlPost
     *
     * Validate an invoice by xml.
     *
     */
    public function testInvoiceV1SendValidateXmlPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for invoiceV1SendXmlPost
     *
     * Add an invoice by xml.
     *
     */
    public function testInvoiceV1SendXmlPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
